spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ewm_db
    username: ewm_user
    password: ewm_pass
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
