services:
  stats-server:
    build:
      context: ./stats-service/stats-server
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats_db
      SPRING_DATASOURCE_USERNAME: stats_user
      SPRING_DATASOURCE_PASSWORD: stats_pass
    depends_on:
      - stats-db

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: stats_user
      POSTGRES_PASSWORD: stats_pass
      POSTGRES_DB: stats_db
    ports:
      - "5432:5432"

  ewm-service:
    build:
      context: ./ewm-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm_db
      SPRING_DATASOURCE_USERNAME: ewm_user
      SPRING_DATASOURCE_PASSWORD: ewm_pass
    depends_on:
      - ewm-db

  ewm-db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ewm_user
      POSTGRES_PASSWORD: ewm_pass
      POSTGRES_DB: ewm_db